[package]
name = "rustblog"
version = "0.1.0"
authors = ["Amritanshu Pandey <amp.msit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.7.1"
maud = "*"
toml = "0.5.6"
glob = "0.3.0"